theme = "modus_vivendi"
# theme = "tokyonight_night"
# theme = "cyberdream"

[editor]
line-number = "relative"
auto-completion = true
auto-format = false
bufferline = "always"

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.indent-guides]
render = true
character = "┆" # Some characters that work well: "▏", "┆", "┊", "⸽"


[keys.insert]
j = { k = "normal_mode" } # Maps `jk` to exit insert mode.
C-h = "move_char_left"
C-l = "move_char_right" # Useful to jump over closing parenthesises.
